"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
"""

upperBound=input("What is the upper bound? ")

total = 0
num1 = 1
num2 = 2
num3 = 3

# one can prove that every third number in the sequence is even
# so we only need to check that the next number is less than upperBound

while num2 < upperBound :
    total += num2
    num1=num2+num3
    num2=num3+num1
    num3=num1+num2

print total
